### ISSUE TITLE
[JOSS Review] Documentation example not functionnal

### ISSUE THREAD

**Issue by stella-bourdin** [daniloceano/CycloPhaser#40]
Hello,
This issue arises from the JOSS review ongoing here: https://github.com/openjournals/joss-reviews/issues/7363

The example provided in the documentation (https://cyclophaser.readthedocs.io/en/latest/usage.html) does not work because:
Already raised:
1. Dependencies were not installed when installing the package (https://github.com/daniloceano/CycloPhaser/issues/38)
2. Test file path is not working (https://github.com/daniloceano/CycloPhaser/issues/39)
Additional issue: 
3. Column name in the example file is wrong: column `min_zeta_850`does not exist in the example file. Switching to `min_max_zeta_850`works. 
Just changing this name in the example once 1 & 2 are treated would fix it.

**Comment by daniloceano** [comment]
Hi @stella-bourdin, 

Thank you again for your feedback. I’ve addressed the final issue regarding the column name in the example. The correct column name is min_max_zeta_850, and I’ve updated the usage documentation accordingly to reflect this change.

Since the other two issues (dependencies installation and test file path) were already resolved, everything should now be in order.

Feel free to test the updated example, and let me know if anything else comes up!

Best regards,
Danilo

**Comment by stella-bourdin** [comment]
Hi, Thank you for treating these. I can confirm the example now works directly!
